# Custom Language File for Launcher Customizer

[ejs.app]
title = "Fun And Chill Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ifalnou/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/ifalnou/HeliosLauncher"
supportLink = "https://github.com/ifalnou/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue !"
welcomeDescription = ""
welcomeDescCTA = ""
